CREATE TABLE "live-feedback-wall_message" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "live-feedback-wall_message_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"roomId" integer NOT NULL,
	"content" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"deletedAt" timestamp with time zone,
	"deleted" boolean DEFAULT false NOT NULL
);
--> statement-breakpoint
CREATE TABLE "live-feedback-wall_room" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "live-feedback-wall_room_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"roomCode" varchar(7) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	"userId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "live-feedback-wall_user" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "live-feedback-wall_user_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"email" varchar(256) NOT NULL,
	"password" varchar(256) NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone,
	CONSTRAINT "live-feedback-wall_user_email_unique" UNIQUE("email")
);
--> statement-breakpoint
DROP TABLE "live-feedback-wall_post" CASCADE;--> statement-breakpoint
ALTER TABLE "live-feedback-wall_message" ADD CONSTRAINT "live-feedback-wall_message_roomId_live-feedback-wall_room_id_fk" FOREIGN KEY ("roomId") REFERENCES "public"."live-feedback-wall_room"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "live-feedback-wall_room" ADD CONSTRAINT "live-feedback-wall_room_userId_live-feedback-wall_user_id_fk" FOREIGN KEY ("userId") REFERENCES "public"."live-feedback-wall_user"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "room_id_idx" ON "live-feedback-wall_message" USING btree ("roomId");--> statement-breakpoint
CREATE INDEX "name_idx" ON "live-feedback-wall_room" USING btree ("name");--> statement-breakpoint
CREATE INDEX "email_idx" ON "live-feedback-wall_user" USING btree ("email");