-- ============================================
-- Live Feedback Wall - Dialekt PostgreSQL
-- ============================================
-- Model bazy danych z wykorzystaniem typów
-- i funkcjonalności specyficznych dla PostgreSQL 14+.

-- Tabela użytkowników (organizatorów)
CREATE TABLE "user" (
    id              TEXT            PRIMARY KEY,
    email           TEXT            NOT NULL,
    name            TEXT            NOT NULL,
    email_verified  BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT now(),
    CONSTRAINT user_email_unique UNIQUE (email)
);

-- Tabela sesji użytkowników
CREATE TABLE "session" (
    id              TEXT            PRIMARY KEY,
    expires_at      TIMESTAMP       NOT NULL,
    token           TEXT            NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT now(),
    updated_at      TIMESTAMP       NOT NULL DEFAULT now(),
    ip_address      TEXT,
    user_agent      TEXT,
    user_id         TEXT            NOT NULL,
    CONSTRAINT session_token_unique UNIQUE (token),
    CONSTRAINT session_user_id_fk
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela kont uwierzytelniania (providery: email/hasło, OAuth)
CREATE TABLE "account" (
    id                          TEXT        PRIMARY KEY,
    account_id                  TEXT        NOT NULL,
    provider_id                 TEXT        NOT NULL,
    user_id                     TEXT        NOT NULL,
    access_token                TEXT,
    refresh_token               TEXT,
    id_token                    TEXT,
    access_token_expires_at     TIMESTAMP,
    refresh_token_expires_at    TIMESTAMP,
    scope                       TEXT,
    password                    TEXT,
    created_at                  TIMESTAMP   NOT NULL DEFAULT now(),
    updated_at                  TIMESTAMP   NOT NULL DEFAULT now(),
    CONSTRAINT account_user_id_fk
        FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela kodów weryfikacyjnych (email)
CREATE TABLE "verification" (
    id              TEXT        PRIMARY KEY,
    identifier      TEXT        NOT NULL,
    value           TEXT        NOT NULL,
    expires_at      TIMESTAMP   NOT NULL,
    created_at      TIMESTAMP   DEFAULT now(),
    updated_at      TIMESTAMP   DEFAULT now()
);

-- Tabela pokoi (feedback wall)
-- Używa GENERATED BY DEFAULT AS IDENTITY (PostgreSQL 10+)
-- oraz TIMESTAMP WITH TIME ZONE dla poprawnej obsługi stref czasowych
CREATE TABLE "room" (
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
                (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    name        VARCHAR(256)                NOT NULL,
    "roomCode"  VARCHAR(7)                  NOT NULL UNIQUE,
    "createdAt" TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE,
    "userId"    TEXT                        NOT NULL,
    CONSTRAINT room_user_id_fk
        FOREIGN KEY ("userId") REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela wiadomości
-- Wspiera soft-delete (deleted + deletedAt)
CREATE TABLE "message" (
    id          INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
                (INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
    "roomId"    INTEGER                     NOT NULL,
    content     VARCHAR(256)                NOT NULL,
    sender      VARCHAR(256)                NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP WITH TIME ZONE,
    "deletedAt" TIMESTAMP WITH TIME ZONE,
    deleted     BOOLEAN                     NOT NULL DEFAULT FALSE,
    CONSTRAINT message_room_id_fk
        FOREIGN KEY ("roomId") REFERENCES "room"(id) ON DELETE CASCADE
);

-- Indeksy (optymalizacja zapytań)
CREATE INDEX idx_room_user_id ON "room"("userId");
CREATE INDEX idx_room_code ON "room"("roomCode");
CREATE INDEX idx_message_room_id ON "message"("roomId");
CREATE INDEX idx_message_created_at ON "message"("createdAt");
CREATE INDEX idx_session_user_id ON "session"(user_id);
CREATE INDEX idx_session_token ON "session"(token);
