-- ============================================
-- Live Feedback Wall - Standard SQL (ANSI SQL)
-- ============================================
-- Model bazy danych w standardzie SQL (ANSI/ISO)
-- niezależny od konkretnego systemu DBMS.

-- Tabela użytkowników (organizatorów)
CREATE TABLE "user" (
    id              VARCHAR(255)    PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL UNIQUE,
    name            VARCHAR(255)    NOT NULL,
    email_verified  BOOLEAN         NOT NULL DEFAULT FALSE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- Tabela sesji użytkowników
CREATE TABLE "session" (
    id              VARCHAR(255)    PRIMARY KEY,
    expires_at      TIMESTAMP       NOT NULL,
    token           VARCHAR(255)    NOT NULL UNIQUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    ip_address      VARCHAR(45),
    user_agent      VARCHAR(512),
    user_id         VARCHAR(255)    NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela kont uwierzytelniania (providery: email/hasło, OAuth)
CREATE TABLE "account" (
    id                          VARCHAR(255)    PRIMARY KEY,
    account_id                  VARCHAR(255)    NOT NULL,
    provider_id                 VARCHAR(255)    NOT NULL,
    user_id                     VARCHAR(255)    NOT NULL,
    access_token                VARCHAR(512),
    refresh_token               VARCHAR(512),
    id_token                    VARCHAR(512),
    access_token_expires_at     TIMESTAMP,
    refresh_token_expires_at    TIMESTAMP,
    scope                       VARCHAR(255),
    password                    VARCHAR(255),
    created_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela kodów weryfikacyjnych (email)
CREATE TABLE "verification" (
    id              VARCHAR(255)    PRIMARY KEY,
    identifier      VARCHAR(255)    NOT NULL,
    value           VARCHAR(512)    NOT NULL,
    expires_at      TIMESTAMP       NOT NULL,
    created_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP       DEFAULT CURRENT_TIMESTAMP
);

-- Tabela pokoi (feedback wall)
CREATE TABLE "room" (
    id              INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name            VARCHAR(256)    NOT NULL,
    room_code       VARCHAR(7)      NOT NULL UNIQUE,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    user_id         VARCHAR(255)    NOT NULL,
    FOREIGN KEY (user_id) REFERENCES "user"(id) ON DELETE CASCADE
);

-- Tabela wiadomości
CREATE TABLE "message" (
    id              INTEGER         PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_id         INTEGER         NOT NULL,
    content         VARCHAR(256)    NOT NULL,
    sender          VARCHAR(256)    NOT NULL,
    created_at      TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP,
    deleted_at      TIMESTAMP,
    deleted         BOOLEAN         NOT NULL DEFAULT FALSE,
    FOREIGN KEY (room_id) REFERENCES "room"(id) ON DELETE CASCADE
);
